site_name: hledger-lots
site_url: https://edkedk99.github.io/hledger-lots/
repo_url: https://github.com/edkedk99/hledger-lots
strict: true
remote_name: github

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top

nav:
    - Home: README.md
    - Usage: usage.md
    - Download Market Prices: market_prices.md
    - Output examples: output.md
    - Unit tests: tests.md

markdown_extensions:
  - attr_list
  - mkdocs-click
  - toc:
        permalink: "#"



