site_name: hledger-fifo
site_url: https://edkedk99.github.io/hledger-fifo/
repo_url: https://github.com/edkedk99/hledger-fifo
strict: true
remote_name: github

theme: readthedocs
watch:
  - hledger_fifo
nav:
    - Home: README.md
    - Usage: usage.md
    - Output examples: output.md

markdown_extensions:
  - attr_list
  - mkdocs-click
  - toc:
        permalink: "#"


